### ISSUE TITLE
Episode Ordering Error

### ISSUE THREAD

**Issue by Atticus837** [AceFire6/ordered-arrowverse#4]
Supergirl S01E04 and S01E05 have their episode labels misordered. The titles, dates and places in the list are correct, but episode 4 says S01E05 and vice versa.

**Comment by AceFire6** [comment]
Hi @Atticus837. Thank you for letting me know. Were you using any of the filtering options or newest first?

**Comment by Atticus837** [comment]
Hi @AceFire6,
No filters, set to oldest first. Haven't checked if the two episodes are mislabelled in any other configuration, I suppose I shouldn't have assumed that they were.

Have fun!

**Comment by AceFire6** [comment]
They definitely shouldn't be different but you never know. Thanks for the additional information. I'll see if I can get it fixed asap 👍

**Comment by AceFire6** [comment]
@Atticus837 I've found the source of the issue. I do ordering based on the air date of each episode. [The air date of episode 4 was pushed back because of attacks in Paris in 2015](https://en.wikipedia.org/wiki/Livewire_(Supergirl)#Production).

I'm not sure what do about this and would appreciate any suggestions you have. 

I could add an exception (in the same way that there is an exception for Arrow S03E17 and Flash S01E17).

**Comment by Atticus837** [comment]
Since it's a one off event I'd suggest an exception is your best choice,
but make sure you're only fixing the label. If memory serves me right the
title, air date etc. were all correct.

Perhaps you could code in a check script that makes sure new episodes are
the next in a given show, and either adjusts or warns you if this happens
in future?
Other than that I doubt there's much you can do.

**Comment by AceFire6** [comment]
I might consider adding an exception in the future but for now I'll leave it as is
